### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by pfrenssen**
Fix typo.

### CODE REVIEW

**Comment by ademarco** [comment]
:+1:

**Comment by tatarbj** [comment]
@pfrenssen ++

**Comment by dspinellis** [comment]
Thank you for the sharp-eyed correction!  Note that this repository is automatically generated, and therefore not the right place to send pull requests.  Please verify the correction against the scanned copy of the document, and if the error was in the transcription (and not in the original document), please submit a pull request for a _script_ that fixes the problem on the https://github.com/dspinellis/unix-history-make repo.

**Comment by samrocketman** [comment]
This seems like abuse of SCM.  What's the point of having a repository "automatically generated" from another repository and store it?  Perhaps I'm missing something.

I've read the synopsis in unit-history-make.  Is there an sccs hosted somewhere that you're continually regenerating from?

**Comment by dspinellis** [comment]
[This script](https://github.com/dspinellis/unix-history-make/blob/master/src/import-dir.pl) imports the snapshots and the SCCS repository.  The repository is automatically generated in order to allow the metadata and techniques used for the import to be improved over time. You might want to see [this conference paper](http://www.dmst.aueb.gr/dds/pubs/conf/2015-MSR-Unix-History/html/Spi15c.html) for an overview of the project and its goals.

**Comment by samrocketman** [comment]
Great, I'll read them.

**Pull request closed without merging**
